### ISSUE TITLE
Adjust Display and Sizing of Pictures in TodayPic Component

### ISSUE THREAD

**Issue by kristenking** [hjkmines/resource_library#54]
In the TodayPic component, currently the pictures are displayed in a column, one on top of another. We would like to improve this by having them display in a grid layout that will adjust depending on the size of the viewport.

Things to work on:

1. Modify the grid layout to display images side by side. The exact number of images per row should be responsive, depending on the size of the screen. This might be 2-3 pictures in a row for larger screens.

2. Adjust the sizes of the images so they fit neatly within the grid. The images should scale responsively with the size of the grid cells.

3. Standardize the size of the arrow icon and the font size of "more laughs" text at the bottom of the component. They should match the sizes used in other components.

**Comment by thomas065** [comment]
issues fixed on PR,
https://github.com/hjkmines/resource_library/pull/56
